### ISSUE TITLE
Add task names to slurm jobs

### ISSUE THREAD

**Issue by anttonalberdi** [earthhologenome/EHI_bioinformatics#22]
To avoid all jobs in the slurm queue to be named just snakemake

For example by declaring a job name in the snakemake rule:
    params:
        jobname="ehi.pr",

And the using the following in the snakemake cluster argument.
-J {params.jobname}

**Comment by EisenRa** [comment]
I found an easier solution which involves changing only the call to snakemake:

Adding this flag:
```
--job-name=EHI-PRB001-{rule}
```

Yields the following:
```
742125  cpuqueue   EHI-PRB001-fetch_host_genome
```

I'll implement this in the launching script in AirTable :)
