### ISSUE TITLE
Split GTDBtk and Airtable in different rules

### ISSUE THREAD

**Issue by anttonalberdi** [earthhologenome/EHI_bioinformatics#25]
The rule gtdbtk contains a final step of uploading the report to Airtable. Recently, this final step failed, but snakemake removed all gtdbtk-produced files. Ideally, a new rule should be defined, to avoid an Airtable connection issue to spoil all the computational work carried out by gtdbtk.

**Comment by EisenRa** [comment]
I've been having some issues with the python dependencies in the gtdbtk rule (guessing it's to do with updating the snakemake/mamba version...). I've shifted the MAG stats API call to the assembly/coassembly summary rule, which should fix the issue. 

fa1791ea1da91e55858b9b4294d848685642edd1
