### ISSUE TITLE
Adjust MAG download time in DMB to the number of MAGs

### ISSUE THREAD

**Issue by anttonalberdi** [earthhologenome/EHI_bioinformatics#26]
The number of MAGs needed to be dereplicated is available at the DMB table, so it would be desirable to adjust the time-limit of the rule to that number. DMBs with >1500 MAGs often fail in the downloading step.

**Comment by EisenRa** [comment]
Fixed with [bc827d3](https://github.com/earthhologenome/EHI_bioinformatics/commit/bc827d3017e435c0977b1c5c2b90dc3e4396cd6a)
